CharacterLoadouts = LibStub("AceAddon-3.0"):NewAddon("CharacterLoadouts")
cl_AceDB = LibStub("AceDB-3.0")
cl_AceDBOptions = LibStub("AceDBOptions-3.0")
cl_AceConsole = LibStub("AceConsole-3.0")
cl_AceGUI = LibStub("AceGUI-3.0")
cl_AceConfig = LibStub("AceConfig-3.0")
cl_AceConfigDialog = LibStub("AceConfigDialog-3.0")
